---
cgit_url: https://bogomips.org/sleepy_penguin.git
git_url: https://bogomips.org/sleepy_penguin.git
rdoc_url: https://bogomips.org/sleepy_penguin/
ml_url: https://bogomips.org/sleepy-penguin/
public_email: sleepy-penguin@bogomips.org
